### ISSUE TITLE
iPython 8.2.0 not compatible with vim-ipython-cell

### ISSUE THREAD

**Issue by spencer-tb** [hanschen/vim-ipython-cell#38]
I believe this issue: https://github.com/ipython/ipython/issues/13622, is preventing vim-ipython-cell to work with ipython==8.2.0. 

Due to issues with '%paste -q' and '%cpaste -q'.

It works in ipython==8.1.1, so recommend using this version until it is fixed in ipython==8.2.0.

**Comment by hanschen** [comment]
Thanks for the notice. I get the same `ERROR! Session/line number was not unique in database. History logging moved to new session x` error message, but the code execution still seems to work. Is it the same for you?

I've added a line to the README about this issue.

**Comment by hanschen** [comment]
The issue seems to be fixed in IPython 8.4.0. Can you still reproduce the issue?

EDIT: Nevermind, it seems like the issue's still here as well.

**Comment by AchmadFathoni** [comment]
> The issue seems to be fixed in IPython 8.4.0. Is it the same for you?

Still same for me

**Comment by Mickychen00** [comment]
Same for me in IPYHON 8.4.0

**Comment by CosmosAtlas** [comment]
[This commit](https://github.com/ipython/ipython/pull/13763) should fix the issue with the new release of 8.6.0.

I don't personally use this plugin, can anyone confirm?

**Comment by hanschen** [comment]
> [This commit](https://github.com/ipython/ipython/pull/13763) should fix the issue with the new release of 8.6.0.
> 
> I don't personally use this plugin, can anyone confirm?

@CosmosAtlas Many thanks for the fix. :) The error seems to be gone for `%cpaste -q`, but I unfortunately still get an error when running `%paste -q`:

```
In [2]: %paste -q
test

ERROR! Session/line number was not unique in database. History logging moved to new session 2188
```

```bash
$ ipython --version
8.6.0
```

**Comment by hanschen** [comment]
The issue [has now been fixed](https://github.com/ipython/ipython/pull/13868) in the latest version of IPython (8.8.0 and newer). I have [moved the information about this issue to the FAQ](https://github.com/hanschen/vim-ipython-cell/commit/0367936adddeea95091f6d361263ed0adfcdfd71).
