### ISSUE TITLE
Vundle installation error 

### ISSUE THREAD

**Issue by deboraycb** [hanschen/vim-ipython-cell#45]
Hi,

I am getting the following error when trying to install using Vundle:
```
Error detected while processing /home/dbrandt/.vim/bundle/vim-ipython-cell/plugin/ipython-cell.vim:
line  120:
E121: Undefined variable: v:t_string
E15: Invalid expression: type(g:ipython_cell_tag) == v:t_string
line  126:
E121: Undefined variable: s:ipython_cell_tag_list
E15: Invalid expression: s:ipython_cell_tag_list
```
Any clues about where is this coming from?
Thanks!
Debora

**Comment by hanschen** [comment]
Seems like `v:t_string` was introduced in Vim version 7.4.2071, so I guess you're using an older version.

I've pushed a fix to the master branch. Could you try again and see if it works now?

**Comment by deboraycb** [comment]
Thank you!! I am not getting an installation error any more but for some reason the plugin is still not working for me. It works on my other computer so maybe it's another software version incompatibility. I updated vim and it didn't help. But anyway thanks for fixing the installation error so quickly!

**Comment by deboraycb** [comment]
Actually, the plugin is no longer working in the computer where it used to work! Whenever I try to send lines via tmux, it only sends the same line (one that is not even in my current vim file, it was in a previous vim file I had opened). Not sure how it got stuck in this line!

**Comment by hanschen** [comment]
Hm, that's strange. Did you update the plugin on the other computer and it stopped working after the update?

My guess is that the line it sends is whatever is in your clipboard. If you paste with e.g. Ctrl-v (in another text editor or in a text box), is that the line it pastes? If so, the copying doesn't work for some reason.

If you type `vim --version`, do you see `+clipboard` in the output?

What exactly doesn't work on the first computer? Can you run commands such as `:IPythonCellRun`?

**Comment by deboraycb** [comment]
Yes, I did update the plugin in computer 2 and then it stopped working. The line is not on my clipboard (if I ctrl-v in another editor, nothing pastes, but vim keeps sending that same line to my other tmux panel, no matter if I close an reopen the terminal or do PluginUpdate). So weird.

I do not see `+clipboard` in the output of `vim --version`. Should I?

In computer 1, that command gives me the error message `E492: Not an editor command: IPythonCellRun`

**Comment by deboraycb** [comment]
Hi again,

I now have `+clipboard` in vim in my computer # 2, but that same line keeps getting sent across tmux.

**Comment by hanschen** [comment]
Computer 2:

I wonder if it's the most recent change that broke things, which seems unlikely to me. If you run e.g. `:IPythonCellRun` on that computer, does it work, or do you also get the same line again?

Does it send `%paste -q` for `IPythonCellExecuteCell`?

What do you get if you run `SlimeSendCurrentLine` on a line of code?

Computer 1:

Do you have the plugin in the Vundle plugin directory (I believe it should be `~/.vim/bundle/` - do you have a `vim-ipython-cell` in it)?

If you do, you could try to remove that directory and run `:PluginInstall` again.

Does vim have Python support (does `:echo has('python')` or `:echo has('python3')` return `1`)?

There are some other things to check for, which are mentioned in the [FAQ](https://github.com/hanschen/vim-ipython-cell#faq).

**Comment by deboraycb** [comment]
Computer2:
All of the commands you suggested send the same line. `:SlimeSendCurrentLine` sends it once;  `:IPythonCellRun`  and 
`:IPythonCellExecuteCell` both send the same line 3 times.

Computer1:
- I deleted the directory, ran `:PluginInstall`, and things are still the same
- Apparently vim does not have Python support (both commands return `0`). I reinstalled vim today (version9) and I'm not sure if this broke things.

**Comment by hanschen** [comment]
> Computer2:
All of the commands you suggested send the same line. :SlimeSendCurrentLine sends it once; :IPythonCellRun and
:IPythonCellExecuteCell both send the same line 3 times.

In that case, it's an issue related to vim-slime and likely not with this plugin. You could try to ask for help there: https://github.com/jpalardy/vim-slime
It could also be worth to make sure you have everything configured correctly for Tmux: https://github.com/jpalardy/vim-slime

> Computer1:
>
>    Apparently vim does not have Python support (both commands return 0). I reinstalled vim today (version9) and I'm not sure if this broke things.

That's the issue then. Did you compile Vim by yourself? If so, make sure you specify the `--enable-pythoninterp` and/or `--enable-python3interp` flags during configure. See e.g. https://vi.stackexchange.com/questions/11526/how-to-enable-python-feature-in-vim.

**Comment by deboraycb** [comment]
ok! I'll check those resources. Thanks so much for your help and patience! I updated some things and I guess now I lost control of where things broke, but your tips were great.
